name: main-deployment

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SSH_URL }}
          username: ${{ secrets.REMOTE_SSH_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd ${{ secrets.REMOTE_APP_PATH }}
            git switch main
            git pull
            npm install
            echo "NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}" >> .env
            echo "NEXT_PUBLIC_KAKAO_API_KEY=${{ secrets.NEXT_PUBLIC_KAKAO_API_KEY }}" >> .env
            echo "NEXT_PUBLIC_KAKAO_REST_API_KEY=${{ secrets.NEXT_PUBLIC_KAKAO_REST_API_KEY }}" >> .env
            echo "NEXT_PUBLIC_KAKAO_SHARE_API=${{ secrets.NEXT_PUBLIC_KAKAO_SHARE_API }}" >> .env
             echo "NEXT_PUBLIC_GOOGLE_ANALYTICS=${{ secrets.NEXT_PUBLIC_GOOGLE_ANALYTICS }}" >> .env
            npm run build
            pm2 restart all

      - name: Notify Discord
        run: |
          curl -H "Content-Type: application/json" \
               -d '{"content": "✅ Deployment to production is complete!"}' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
